### PR TITLE
Add shadow to text in nav and fix dropdown

### PR DESCRIPTION
**Pull request by MuriloucoLouco**
The text in the nav component blended with the background if it was too clear. Also, the wrapper 100% width made the dropdown be ordered in form of a column instead of a row.

### CODE REVIEW

**Comment by kunaljainwin** [comment]
Please star the repo i want to keep improving this project

**Comment by kunaljainwin** [comment]
Thanks for fixing the dropdown in center and i fixed the  movies listing issue. I misunderstood earlier

**Comment by kunaljainwin** [comment]
Did you got this pull reqeust counted in hacktoberfest

**Comment by MuriloucoLouco** [comment]
Yes. Although I'm still waiting for it to be validated by the hacktoberfest team

**Pull request merged**
