### PR TITLE
feat: add custom scrollbar

### PR DESCRIPTION
**Pull request by M0nicaVaz**
Contribuiting with #14 

Added scrollbar custom style!

### CODE REVIEW

**Comment by kunaljainwin** [comment]
Looks something between fine <-> good  to me i will merge but remove the bottom scroll bar theress no need of it.
Regards, Kunal

**Comment by kunaljainwin** [comment]
Also can you add something similar to this | Yes, its from your portforlio website
image
above my dropdown

**Comment by M0nicaVaz** [comment]
> Also can you add something similar to this | Yes, its from your portforlio website image above my dropdown

Sure, what do you have in mind? Like a tooltip with something written in it?

**Comment by kunaljainwin** [comment]
My mind
![image](https://user-images.githubusercontent.com/72144717/196022139-6484883d-df7c-4723-a3dc-9a67c8ba0cd8.png
@M0nicaVaz Sure tooltip with something written will work and you can add a background to the info text as well 

But firstremove that extra scrollbar at bottom so that i  can merge it👍

**Pull request merged**
